const { contextBridge, ipcRenderer } = require('electron');
const fs = require('fs');
const path = require('path');

// Generated by scripts/generate-build-info.js (prestart/prepack/predist —
// see package.json) so a running app's footer can be matched back to an
// exact commit instead of guessing whether it's a stale build. Read here
// rather than over IPC since preload already has full Node access and
// this is static for the lifetime of the process.
function loadBuildInfo() {
  try {
    return JSON.parse(fs.readFileSync(path.join(__dirname, '../main/build-info.json'), 'utf8'));
  } catch {
    return { buildNumber: '0', commit: 'unknown', builtAt: null };
  }
}

contextBridge.exposeInMainWorld('slopinator', {
  version: process.env.npm_package_version,
  buildInfo: loadBuildInfo(),
  pickInputFile: () => ipcRenderer.invoke('pick-input-file'),
  getPreviewPath: (trackId) => ipcRenderer.invoke('get-preview-path', trackId),
  runMaster: (args) => ipcRenderer.invoke('run-master', args),
  runTranscode: (args) => ipcRenderer.invoke('run-transcode', args),
  runMasterBatch: (args) => ipcRenderer.invoke('run-master-batch', args),
  classifyPath: (path) => ipcRenderer.invoke('classify-path', path),
  libraryList: () => ipcRenderer.invoke('library-list'),
  libraryAdd: (filePath) => ipcRenderer.invoke('library-add', filePath),
  libraryUpdate: (id, patch) => ipcRenderer.invoke('library-update', { id, patch }),
  libraryRemove: (id) => ipcRenderer.invoke('library-remove', id),
  libraryAnalyze: (id) => ipcRenderer.invoke('library-analyze', id),
  getPeaks: (filePath, buckets) => ipcRenderer.invoke('get-peaks', { filePath, buckets }),
  pickImportFiles: () => ipcRenderer.invoke('pick-import-files'),
  pickExportFolder: () => ipcRenderer.invoke('pick-export-folder'),
  presetsList: () => ipcRenderer.invoke('presets-list'),
  presetsSave: (name, params) => ipcRenderer.invoke('presets-save', { name, params }),
  presetsDelete: (name) => ipcRenderer.invoke('presets-delete', name),
  libraryImport: (paths) => ipcRenderer.invoke('library-import', paths),
  onMasterLog: (callback) => {
    const listener = (_event, payload) => callback(payload);
    ipcRenderer.on('master-log', listener);
    return () => ipcRenderer.removeListener('master-log', listener);
  },
});
