const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('slopinator', {
  version: process.env.npm_package_version,
  // Generated by scripts/generate-build-info.js (prestart/prepack/predist
  // — see package.json). Read via IPC, not a direct require('fs') here —
  // preload runs under Electron's default sandboxed preload (Electron
  // 20+), which has no generic Node require() beyond require('electron')
  // itself; reaching for 'fs'/'path' directly throws and silently kills
  // the entire preload script before contextBridge ever runs, which is
  // exactly what broke every window.slopinator.* call, not just this one.
  getBuildInfo: () => ipcRenderer.invoke('get-build-info'),
  pickInputFile: () => ipcRenderer.invoke('pick-input-file'),
  getPreviewPath: (trackId) => ipcRenderer.invoke('get-preview-path', trackId),
  runMaster: (args) => ipcRenderer.invoke('run-master', args),
  runTranscode: (args) => ipcRenderer.invoke('run-transcode', args),
  runMasterBatch: (args) => ipcRenderer.invoke('run-master-batch', args),
  classifyPath: (path) => ipcRenderer.invoke('classify-path', path),
  libraryList: () => ipcRenderer.invoke('library-list'),
  libraryAdd: (filePath) => ipcRenderer.invoke('library-add', filePath),
  libraryUpdate: (id, patch) => ipcRenderer.invoke('library-update', { id, patch }),
  libraryRemove: (id) => ipcRenderer.invoke('library-remove', id),
  libraryAnalyze: (id) => ipcRenderer.invoke('library-analyze', id),
  getPeaks: (filePath, buckets) => ipcRenderer.invoke('get-peaks', { filePath, buckets }),
  pickImportFiles: () => ipcRenderer.invoke('pick-import-files'),
  pickExportFolder: () => ipcRenderer.invoke('pick-export-folder'),
  presetsList: () => ipcRenderer.invoke('presets-list'),
  presetsSave: (name, params) => ipcRenderer.invoke('presets-save', { name, params }),
  presetsDelete: (name) => ipcRenderer.invoke('presets-delete', name),
  libraryImport: (paths) => ipcRenderer.invoke('library-import', paths),
  // Electron 32+ stopped patching a real filesystem path onto dropped
  // File objects (the old, now-removed File.path) — this is the
  // replacement, only callable from preload/main, never the renderer
  // directly. See docs/context.md's Electron 43 upgrade gotcha.
  getPathForFile: (file) => webUtils.getPathForFile(file),
  onMasterLog: (callback) => {
    const listener = (_event, payload) => callback(payload);
    ipcRenderer.on('master-log', listener);
    return () => ipcRenderer.removeListener('master-log', listener);
  },
  onLibraryImportProgress: (callback) => {
    const listener = (_event, payload) => callback(payload);
    ipcRenderer.on('library-import-progress', listener);
    return () => ipcRenderer.removeListener('library-import-progress', listener);
  },
});
